flomesh-io/fsm

.github/workflows/build-pipy-nonroot.yml

ci: add workflow for building pipy nonroot image

---

.github/workflows/build-pipy-nonroot.yml
dockerfiles/Dockerfile.pipy-nonroot

build: add Dockerfile for building pipy nonroot image

---

scripts/release-notes.sh

fix: CRD Update section is not generated correctly in release notes

---

scripts/port-forward-jaeger.sh

| Demo                       | [x] |
| …

update port forwarding shell to fix jaeger pod label

---

pkg/apis/shared_types.go

Fix issue #32 
| Ingress                    | [x] |
| Upgrade …

Rollback change for balance algorithm shortening

---

scripts/port-forward-all.sh

| Demo                       | [x] |
| …

fix port fordwarding script

---

.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
charts/fsm/README.md
charts/fsm/templates/fsm-flb-secret.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
pkg/constants/constants.go
pkg/controllers/flb/service_controller.go
pkg/webhook/flb/secret/webhook.go

feat: cherry-pick FLB changes from fsm-classic

---

.github/workflows/main.yml
Makefile
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml

ci: checks if CRD YAMLs are update to date

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
go.sum
pkg/apis/config/v1alpha1/mesh_config.go
pkg/apis/config/v1alpha2/mesh_config.go
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/manager/listeners/client.go
pkg/sidecar/providers/pipy/driver/pipy_container.go
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/types.go
tests/e2e/e2e_permissive_test.go

Add RemoteLoggingLevel to MeshConfig
Done …

Add RemoteLoggingLevel to MeshConfig

---

cmd/cli/gateway_disable.go
cmd/cli/gateway_enable.go
cmd/cli/ingress_disable.go
cmd/cli/ingress_enable.go
cmd/cli/ingress_namespaced_disable.go
cmd/cli/ingress_namespaced_enable.go
pkg/utils/log.go

feat: CLI checks if k8s server version meets the minimum requirements of ingress/gateway

---

cmd/cli/egressgateway_enable.go
cmd/cli/flb_enable.go
cmd/cli/ingress_enable.go
cmd/cli/shared.go
pkg/constants/constants.go
pkg/controllers/gateway/v1beta1/gateway_controller.go
pkg/controllers/namespacedingress/v1alpha1/namespacedingress_controller.go

refactor: extract constants for rendering helm chart

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
pkg/apis/config/v1alpha3/mesh_config.go

build: bump pipy to 0.90.3-2

---

pkg/gateway/cache/cache.go

feat: enable fgw debug log if gateway log level is trace/debug

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
go.sum
pkg/apis/config/v1alpha1/mesh_config.go
pkg/apis/config/v1alpha2/mesh_config.go
pkg/apis/config/v1alpha3/mesh_config.go
pkg/messaging/broker.go
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/types.go

1.changed implementation of outbound per-request load balancing
2.change serviceAccessMode's default value to mixed
3.change enableAccessControlPolicy's default value to true
4.upgrade pipy to 0.90.3-38
Done
| Performance …

Changed implementation of outbound per-request load balancing.

---

pkg/controllers/flb/service_controller.go

fix: check if resource revision of svc is changed, ignore processing if it doesn't

---

pkg/webhook/gateway/gateway_webhook.go

fix: nil pointer in Gateway webhook

---

charts/fsm/README.md
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha1/mesh_config.go
pkg/apis/config/v1alpha2/mesh_config.go
pkg/apis/config/v1alpha3/mesh_config.go
pkg/cni/plugin/plugin.go
pkg/configurator/methods.go
pkg/constants/constants.go
pkg/k8s/client.go
pkg/messaging/broker.go
pkg/sidecar/providers/pipy/driver/pipy_container.go
pkg/sidecar/providers/pipy/repo/codebase/dns-main.js
pkg/sidecar/providers/pipy/repo/codebase/logging.js
pkg/sidecar/providers/pipy/repo/codebase/main.js
pkg/sidecar/providers/pipy/repo/codebase/tracing.js
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/types.go

1. move sidecar's ENVs into config.json 
2. add exclusion service feature.
Done …

add exclusion service feature.

---

pkg/constants/constants.go
pkg/controllers/flb/service_controller.go

fix: FLB not able to handle external IP assignment

---

pkg/connector/sink.go

fix virtual service's update error.
Done
| …

fix virtual service's update error.

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/webhook/gateway/gateway_webhook.go
pkg/webhook/grpcroute/grpcroute_webhook.go
pkg/webhook/httproute/httproute_webhook.go
pkg/webhook/tlsroute/tlsproute_webhook.go

feat: add feature flags to enable/disable validating hostnames of GatewayAPI resources

---

pkg/controllers/gateway/v1beta1/gateway_controller.go

fix: gateway address is not updated due to latency of assigning service external IPs

---

cmd/cli/mesh_upgrade.go

feat: add -f/--values option to fsm mesh upgrade command

---

charts/fsm/README.md
charts/fsm/values.yaml

perf: tuning the requests and limit resource quota

---

pkg/webhook/gatewaytls/webhook.go

feat: validate GatewayTLSPolicy upon Gateway listener protocol

---

pkg/webhook/retry/webhook.go

fix: validate status code of retry policy spec

---

pkg/webhook/accesscontrol/webhook.go
pkg/webhook/circuitbreaking/webhook.go
pkg/webhook/faultinjection/webhook.go
pkg/webhook/gatewaytls/webhook.go
pkg/webhook/healthcheck/webhook.go
pkg/webhook/loadbalancer/webhook.go
pkg/webhook/ratelimit/webhook.go
pkg/webhook/retry/webhook.go
pkg/webhook/sessionsticky/webhook.go
pkg/webhook/upstreamtls/webhook.go

fix: fast fail for the wrong target reference

---

pkg/controllers/flb/service_controller.go

feat: append protocol of service port to service key

---

pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/types.go

fix remote log level type
DONE
| Upgrade …

fix remote log level type

---

pkg/sidecar/providers/pipy/repo/policy.go

fix RouteRules order
Done
| Upgrade …

fix RouteRules order

---

.github/workflows/build-pipy-nonroot.yml
dockerfiles/Dockerfile.pipy-debian
dockerfiles/Dockerfile.pipy-nonroot

fix: not able to build pipy nonroot image due to make -j

---

charts/fsm/templates/preset-mesh-config.yaml

add sidecarDisabledMTLS into default meshconfig
Done
| Tests …

add sidecarDisabledMTLS into default meshconfig

---

pkg/apis/policyattachment/v1alpha1/register.go
pkg/constants/constants.go
pkg/controllers/policyattachment/v1alpha1/accesscontrolpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/circuitbreakingpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/faultinjectionpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/gatewaytlspolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/healthcheckpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/internal.go
pkg/controllers/policyattachment/v1alpha1/loadbalancerpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/ratelimitpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/retrypolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/sessionstickypolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/upstreamtlspolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/utils.go
pkg/gateway/cache/methods.go
pkg/gateway/cache/policies.go
pkg/gateway/cache/types.go
pkg/gateway/policy/status/policy_status_processor.go
pkg/gateway/policy/status/service_policy_status_processor.go
pkg/gateway/policy/status/types.go
pkg/gateway/policy/status/utils.go
pkg/gateway/types/types.go
pkg/gateway/utils/utils.go

refactor: extract status processor for policy attachment

---

pkg/gateway/cache/config.go
pkg/gateway/cache/grpcroute.go
pkg/gateway/cache/httproute.go
pkg/gateway/cache/tcproute.go
pkg/gateway/cache/tlsroute.go
pkg/gateway/cache/types.go
pkg/gateway/cache/udproute.go
pkg/gateway/cache/utils.go
pkg/gateway/fgw/types.go
pkg/gateway/policy/grpc_route_enricher.go
pkg/gateway/policy/hostname_enricher.go
pkg/gateway/policy/http_route_enricher.go
pkg/gateway/policy/port_enrichers.go
pkg/gateway/policy/service_enrichers.go
pkg/gateway/policy/utils.go

feat: merge HTTP/GRPC rules in case the match conditions are equal

---

cmd/fsm-bootstrap/crds/plugin.flomesh.io_pluginchains.yaml
cmd/fsm-bootstrap/crds/plugin.flomesh.io_pluginconfigs.yaml
pkg/apis/plugin/v1alpha1/plugin_chain.go
pkg/apis/plugin/v1alpha1/plugin_config.go
pkg/gen/client/plugin/clientset/versioned/typed/plugin/v1alpha1/fake/fake_plugin_client.go
pkg/gen/client/plugin/clientset/versioned/typed/plugin/v1alpha1/fake/fake_pluginchain.go
pkg/gen/client/plugin/clientset/versioned/typed/plugin/v1alpha1/fake/fake_pluginconfig.go
pkg/gen/client/plugin/clientset/versioned/typed/plugin/v1alpha1/plugin_client.go
pkg/gen/client/plugin/clientset/versioned/typed/plugin/v1alpha1/pluginchain.go
pkg/gen/client/plugin/clientset/versioned/typed/plugin/v1alpha1/pluginconfig.go
pkg/gen/client/plugin/informers/externalversions/plugin/v1alpha1/interface.go
pkg/gen/client/plugin/informers/externalversions/plugin/v1alpha1/pluginchain.go
pkg/gen/client/plugin/informers/externalversions/plugin/v1alpha1/pluginconfig.go
pkg/gen/client/plugin/listers/plugin/v1alpha1/expansion_generated.go
pkg/gen/client/plugin/listers/plugin/v1alpha1/pluginchain.go
pkg/gen/client/plugin/listers/plugin/v1alpha1/pluginconfig.go
pkg/k8s/client.go

restore PluginChain and PluginConfig scope.
Done
| Tests                      | …

restore PluginChain and PluginConfig scope.

---

pkg/gateway/utils/utils.go

fix: listener condition type of programmed

---

pkg/connector/ctok/source.go
pkg/connector/ktoc/source.go
pkg/connector/ktog/gateway.go
pkg/connector/provider/types.go

connector supports grpc protocol.
| …

feat: connector supports grpc protocol.

---

docs/gateway-api-compatibility.md

docs: update GatewayAPI compatibility [skip ci]

---

charts/fsm/Chart.yaml
charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.yaml
charts/gateway/Chart.yaml
charts/gateway/README.md
charts/gateway/values.yaml
charts/namespaced-ingress/Chart.yaml
charts/namespaced-ingress/README.md
charts/namespaced-ingress/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/controllers/flb/service_controller.go
pkg/controllers/servicelb/service_controller.go
pkg/manager/listeners/client.go
pkg/utils/ip.go
pkg/utils/pod.go

feat: FLB supports multiple modes of getting upstreams

---

dockerfiles/Dockerfile.fsm-curl

changed fsm-curl's base image to flomesh/curl:latest
Done
| Tests …

changed fsm-curl's base image to flomesh/curl:latest

---

charts/gateway/templates/service-tcp.yaml
charts/gateway/templates/service-udp.yaml
docs/tests/gateway-api/README.md
pkg/controllers/gateway/v1beta1/gateway_controller.go

feat: gateway supports coexistence of TCP and UDP listener

---

pkg/apis/policyattachment/v1alpha1/doc.go

docs: fix a typo

---

cmd/fsm-bootstrap/fsm-bootstrap.go

fix: assignment entry to nil map

---

cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/catalog/access_control.go
pkg/connector/cli/sync.go
pkg/connector/ctok/sink.go
pkg/connector/ctok/source.go
pkg/connector/ctok/types.go
pkg/connector/provider/consul.go
pkg/connector/provider/types.go
pkg/connector/types.go
pkg/connector/watcher.go
pkg/providers/kube/client.go
pkg/providers/kube/client_test.go
pkg/sidecar/providers/pipy/repo/util.go

1. add check info with consul registration.
2. auto create check service for consul service.
3. use fgw's cluster ip as via gateway for local k8s services.
4. sync with fsm gateway service name's change.
5. fix mixed service access mode.
6. fix access controll.
Done
| Networking                 | [ ] …

fix: cloud connector issuses

---

pkg/connector/ktog/gateway.go

fix fgw http route's hostnames.
Done
| …

fix: fgw http route's hostnames.

---

charts/gateway/README.md
charts/gateway/templates/deployment.yaml
charts/gateway/templates/hpa.yaml
charts/gateway/templates/pod-disruption-budget.yaml
charts/gateway/values.yaml
docs/tests/gateway-api/README.md
pkg/constants/constants.go
pkg/controllers/gateway/v1beta1/gateway_controller.go
pkg/controllers/gateway/v1beta1/utils.go

feat: support setting replicas and resource limits of Gateway

---

charts/gateway/templates/deployment.yaml
charts/gateway/templates/service-tcp.yaml
charts/gateway/templates/service-udp.yaml
docs/tests/gateway-api/README.md

… a Gateway
| Upgrade                    | …

feat: propagate labels and annotations to each resource generated for a gateway

---

cmd/fsm-bootstrap/crds/gateway.flomesh.io_accesscontrolpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_circuitbreakingpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_faultinjectionpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_gatewaytlspolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_healthcheckpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_loadbalancerpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_ratelimitpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_retrypolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_sessionstickypolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_upstreamtlspolicies.yaml
pkg/apis/policyattachment/v1alpha1/accesscontrol.go
pkg/apis/policyattachment/v1alpha1/circuitbreaking.go
pkg/apis/policyattachment/v1alpha1/faultinjection.go
pkg/apis/policyattachment/v1alpha1/gatewaytls.go
pkg/apis/policyattachment/v1alpha1/healthcheck.go
pkg/apis/policyattachment/v1alpha1/loadbalancer.go
pkg/apis/policyattachment/v1alpha1/ratelimit.go
pkg/apis/policyattachment/v1alpha1/retry.go
pkg/apis/policyattachment/v1alpha1/sessionsticky.go
pkg/apis/policyattachment/v1alpha1/upstreamtls.go

…ttachment
| Upgrade                    | …

feat: add label gateway.networking.k8s.io/policy=true to FSM policy attachment

---

charts/fsm/templates/preset-mesh-config.yaml

fix: reduce the possibility of wrongly configuring remote logging

---

pkg/constants/constants.go
pkg/controllers/gateway/v1beta1/gateway_controller.go

fix: status of Gateway IP addresses due to service name changed

---

charts/fsm/README.md
charts/fsm/values.yaml
demo/tail-fsm-consul-connector-logs.sh
demo/tail-fsm-eureka-connector-logs.sh
demo/tail-fsm-gateway-connector-logs.sh
demo/tail-fsm-nacos-connector-logs.sh
pkg/announcements/types.go
pkg/connector/cli/sync.go
pkg/connector/ktoc/broadcast.go
pkg/connector/ktoc/source.go
pkg/connector/ktoc/syncer.go
pkg/connector/provider/eureka.go
pkg/connector/provider/nacos.go
pkg/connector/types.go
pkg/messaging/broker.go
pkg/messaging/types.go
pkg/metricsstore/metricsstore.go

optimized fsm connector.
Done
| Upgrade …

optimized fsm connector.

---

.github/workflows/main.yml
charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/server.go
pkg/sidecar/providers/pipy/repo/types.go

reduce config.json
Done
| Upgrade …

reduce config.json

---

charts/fsm/Chart.yaml
charts/fsm/README.md
charts/fsm/values.yaml
charts/gateway/Chart.yaml
charts/gateway/README.md
charts/gateway/values.yaml
charts/namespaced-ingress/Chart.yaml
charts/namespaced-ingress/README.md
charts/namespaced-ingress/values.yaml
cmd/cli/util.go
pkg/constants/constants.go
pkg/controllers/flb/service_controller.go
pkg/controllers/flb/settings.go
pkg/controllers/flb/tls_secret_controller.go
pkg/controllers/flb/types.go
pkg/controllers/flb/utils.go
pkg/flb/types.go
pkg/flb/utils.go
pkg/manager/reconciler/reconcilers.go
pkg/manager/webhook/webhooks.go
pkg/webhook/flb/service/webhook.go
pkg/webhook/flb/tls/webhook.go

feat: support FLB TLS service

---

.github/workflows/main.yml
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go
tests/e2e/e2e_namespacedingress_test.go
tests/framework/common.go
tests/framework/common_ingress.go
tests/framework/types.go

test: add e2e testcases for Ingress/NamespacedIngress

---

.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
.github/workflows/release.yml
Dockerfile
Makefile
go.mod

build(deps): bump go from 1.21 to 1.22

---

pkg/flb/utils.go

fix: check existence of TLS port in FLB service spec

---

pkg/gateway/cache/config.go
pkg/gateway/cache/types.go
pkg/gateway/cache/utils.go

feat: support headless service without selector

---

pkg/gateway/cache/cache.go
pkg/gateway/cache/endpoints_trigger.go
pkg/gateway/cache/methods.go
pkg/gateway/client.go

fix: watch Endpoints changes for headless service

---

charts/connector/README.md
charts/connector/templates/deployment.yaml
charts/connector/values.schema.json
charts/connector/values.yaml
charts/fsm/README.md
charts/fsm/templates/cleanup-hook.yaml
charts/fsm/templates/fsm-deployment.yaml
charts/fsm/templates/fsm-ingress-deployment.yaml
charts/fsm/templates/fsm-injector-deployment.yaml
charts/fsm/templates/preinstall-hook.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/gateway/README.md
charts/gateway/templates/deployment.yaml
charts/gateway/values.yaml
charts/namespaced-ingress/README.md
charts/namespaced-ingress/templates/deployment.yaml
charts/namespaced-ingress/values.yaml

fix: add resource limit to all containers

---

charts/fsm/README.md
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/apis/connector/v1alpha1/consul.go
pkg/apis/connector/v1alpha1/eureka.go
pkg/apis/connector/v1alpha1/nacos.go
pkg/apis/connector/v1alpha1/types.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/connector/annotation.go
pkg/connector/cli/config.go
pkg/connector/controller.go
pkg/connector/ctok/endpoint.go
pkg/connector/ctok/source.go
pkg/connector/ctok/syncer.go
pkg/connector/ctok/types.go
pkg/connector/discovery.go
pkg/connector/ktoc/source.go
pkg/connector/provider/consul.go
pkg/gateway/cache/config.go
pkg/gateway/cache/types.go
pkg/gateway/cache/utils.go
pkg/manager/listeners/client.go
pkg/sidecar/providers/pipy/driver/pipy_container.go

support forward mode.
Done
| Upgrade …

feat: support forward mode.

---

charts/fsm/README.md
charts/fsm/templates/fsm-deployment.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml

fix: add resource limits to container of pipy repo

---

charts/fsm/templates/fsm-rbac.yaml

fix: add create namespace permission to fsm

---

charts/fsm/templates/fsm-rbac.yaml

fix: add update/patch/delete namespace permission to fsm

---

pkg/connector/ctok/source.go
pkg/connector/ctok/syncer.go
pkg/connector/ctok/types.go
pkg/connector/discovery.go
pkg/connector/ktoc/source.go
pkg/connector/ktoc/syncer.go
pkg/connector/provider/nacos.go
pkg/sidecar/providers/pipy/repo/policy.go

fix invalid cloud service's name.
Done
| …

fix：invalid cloud service's name.

---

pkg/sidecar/providers/pipy/repo/policy.go

fix ruleName for multi services.
fix ruleName for multi services.
| Tests …

fix: ruleName for multi services.

---

pkg/constants/constants.go
pkg/controllers/flb/service_controller.go
pkg/controllers/flb/types.go

feat: new annotations for FLB

---

pkg/controllers/flb/event_handlers.go
pkg/controllers/flb/service_controller.go

feat: delete svc from FLB in case it's not a FLB service anymore

---

README.md

docs: add supported version of GatewayAPI resources

---

pkg/constants/constants.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/controllers/gateway/v1/httproute_controller.go
pkg/controllers/gateway/v1alpha2/grpcroute_controller.go
pkg/controllers/gateway/v1alpha2/tcproute_controller.go
pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
pkg/controllers/gateway/v1alpha2/udproute_controller.go
pkg/controllers/policyattachment/v1alpha1/accesscontrolpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/faultinjectionpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/gatewaytlspolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/ratelimitpolicy_controller.go
pkg/gateway/cache/config.go
pkg/gateway/cache/grpcroute.go
pkg/gateway/cache/httproute.go
pkg/gateway/cache/methods.go
pkg/gateway/cache/policies.go
pkg/gateway/cache/processor.go
pkg/gateway/cache/tcproute.go
pkg/gateway/cache/tlsroute.go
pkg/gateway/cache/types.go
pkg/gateway/cache/udproute.go
pkg/gateway/status/route.go
pkg/gateway/utils/utils.go
pkg/k8s/informers/informers.go
pkg/k8s/informers/types.go

refactor: processing Gateway resources and generating config

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
pkg/apis/config/v1alpha3/mesh_config.go

build: bump pipy from 0.99.1-1 to 1.1.0-1

---

pkg/controllers/flb/service_controller.go

fix: add more variables to compute FLB svc hash

---

pkg/connector/provider/nacos.go

fix nacos password
Done
| Upgrade …

fix: nacos password

---

pkg/controllers/flb/service_controller.go

fix: compute FLB service hash

---

charts/fsm/values.schema.json
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/apis/config/v1alpha3/zz_generated.deepcopy.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/injector/init_container.go
pkg/injector/init_container_test.go
pkg/manager/listeners/client.go
pkg/sidecar/providers/pipy/driver/pipy_container.go
pkg/sidecar/providers/pipy/driver/sidecar.go

fix resources of init container injected with sidecar
Done
| Tests …

fix resources of init container injected with sidecar

---

pkg/controllers/gateway/v1/gateway_controller.go

feat: ensure values from MeshConfig override the values from gateway ParameteRef

---

.github/workflows/main.yml
charts/fsm/README.md
charts/fsm/templates/fsm-rbac.yaml
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/gateway/templates/deployment.yaml
charts/gateway/templates/pod-disruption-budget.yaml
charts/gateway/templates/role.yaml
charts/gateway/templates/rolebinding.yaml
charts/gateway/templates/route.yaml
charts/gateway/templates/service-tcp.yaml
charts/gateway/templates/service-udp.yaml
charts/gateway/templates/serviceaccount.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/connector/ctok/endpoint.go
pkg/controllers/flb/service_controller.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/controllers/servicelb/service_controller.go
pkg/gateway/cache/cache.go
pkg/gateway/cache/endpoints_trigger.go
pkg/gateway/cache/endpointslices_trigger.go
pkg/gateway/cache/methods.go
pkg/gateway/cache/processor.go
pkg/gateway/cache/types.go
pkg/gateway/cache/utils.go
pkg/utils/ip.go
pkg/version/utils.go
tests/e2e/e2e_gatewayapi_test.go

fix: conditionally filter IPs by IPFamilyPolicy 

---

charts/gateway/templates/deployment.yaml
charts/gateway/templates/service-tcp.yaml
charts/gateway/templates/service-udp.yaml

fix: determine if gateway infrastructure is nil

---

pkg/mcs/remote/types.go

[backport] fix: delete multi cluster service and propagate it to all joined clusters

---

pkg/apis/gateway/v1/validation/gatewayclass.go
pkg/webhook/gatewayclass/gatewayclass_webhook.go

fix: ControllerName of gateway class is not editable

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go

build(deps): bump klipper-lb to 0.4.7

---

.github/workflows/main.yml
pkg/connector/provider/eureka.go
pkg/connector/provider/nacos.go
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
tests/e2e/e2e_retry_policy_test.go

fix filterMetadatas
fix DNSResolveDB
Done …

fix: connector issues

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
scripts/k3d-multicluster-deploy-apps.sh
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy to 1.2.0

---

cmd/fsm-bootstrap/fsm-bootstrap.go

fix: merge new CRD with existing CRD, not replace

---

pkg/constants/constants.go
pkg/controllers/flb/service_controller.go
pkg/controllers/flb/types.go

feat: add annotation for FLB session sticky

---

go.mod
go.sum

[security] fix: Classic builder cache poisoning

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
scripts/k3d-multicluster-deploy-apps.sh
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.2.0 to 1.3.0

---

pkg/controllers/gateway/v1/gateway_controller.go
pkg/gateway/processor/v2/backend_tls_policy.go
pkg/gateway/status/routes/processor.go
pkg/gateway/status/status.go

fix: missing updating status of GatewayAPI resources

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/sidecar/providers/pipy/repo/policy.go

1. remove sidecar log level validation.
2. disable Remote Logging SampledFraction.
| Sidecar Injection          | [ …

fix: sidecar log issues

---

charts/connector/templates/deployment.yaml
charts/fsm/README.md
charts/fsm/templates/_helpers.tpl
charts/fsm/templates/fsm-deployment.yaml
charts/fsm/templates/fsm-ingress-deployment.yaml
charts/fsm/templates/fsm-injector-deployment.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/gateway/templates/deployment.yaml
charts/namespaced-ingress/templates/deployment.yaml

fix trust domain.
Done
| Upgrade …

fix trust domain.

---

pkg/gateway/fgw/config.go
pkg/gateway/processor/v2/gateway.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go

feat: generate UUID for each filter instance

---

.github/workflows/build-pipy-euler.yml
dockerfiles/Dockerfile.euler

build: pipy euler image

---

cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filterdefinitions.yaml
cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filters.yaml
cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_listenerfilters.yaml
pkg/apis/extension/v1alpha1/filter.go
pkg/apis/extension/v1alpha1/filterdefinition.go
pkg/apis/extension/v1alpha1/listenerfilter.go
pkg/apis/extension/v1alpha1/shared_types.go
pkg/controllers/extension/v1alpha1/filter_controller.go
pkg/gateway/fgw/config.go
pkg/gateway/fgw/types.go
pkg/gateway/processor/v2/filters.go
pkg/gateway/processor/v2/gateway.go
pkg/gateway/processor/v2/generator.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go

fix: issue of generating config of gateway filters

---

pkg/gateway/status/gw/gateway.go
pkg/gateway/status/types.go

perf: only updating gateway status if needed

---

cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_circuitbreakers.yaml
cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_faultinjections.yaml
cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_metrics.yaml
cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_ratelimits.yaml
pkg/apis/extension/v1alpha1/circuitbreaker.go
pkg/apis/extension/v1alpha1/faultinjection.go
pkg/apis/extension/v1alpha1/metrics.go
pkg/apis/extension/v1alpha1/ratelimit.go

fix: add format validation to field of type metav1.Duration

---

charts/fsm/README.md
charts/fsm/values.yaml
charts/gateway/templates/deployment.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
cmd/fsm-gateway/fsm-gateway.go
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
pkg/constants/constants.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

fix: health check of gateway instance

---

pkg/controllers/policyattachment/v1alpha3/backendtlspolicy_controller.go

fix: use wrapped method to create webhook

---

pkg/gateway/fgw/config.go

fix: convert duration to seconds in policy attachment

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_gatewayconnectors.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/apis/connector/v1alpha1/gateway.go
pkg/catalog/catalog.go
pkg/connector/cli/config.go
pkg/connector/cli/sync.go
pkg/gateway/processor/v2/utils.go
pkg/messaging/broker.go
pkg/sidecar/providers/pipy/repo/codebase/config.js
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/server.go
pkg/sidecar/providers/pipy/repo/types.go

1. Supported optional compression of config.json
2. Integrated isolation policy with fgw.
Done …

Supported optional compression of config.json and integrated isolation policy with fgw

---

.github/workflows/build-pipy-euler.yml
.github/workflows/build-pipy-nonroot.yml

feat: build image on runner of target platform

---

pkg/gateway/fgw/config.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go

feat: GEP-3171 Percentage-based request mirroring

---

pkg/gateway/fgw/config.go

… changes
| Upgrade                    | [ …

feat: generate BackendTLSPolicy config according to gateway-api 1.2.0 changes

---

cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_filters.yaml
cmd/fsm-bootstrap/crds/extension.gateway.flomesh.io_listenerfilters.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_healthcheckpolicies.yaml
cmd/fsm-bootstrap/crds/gateway.flomesh.io_retrypolicies.yaml
pkg/apis/extension/v1alpha1/circuitbreaker.go
pkg/apis/extension/v1alpha1/faultinjection.go
pkg/apis/extension/v1alpha1/filter.go
pkg/apis/extension/v1alpha1/filterconfig.go
pkg/apis/extension/v1alpha1/filterdefinition.go
pkg/apis/extension/v1alpha1/httplog.go
pkg/apis/extension/v1alpha1/listenerfilter.go
pkg/apis/extension/v1alpha1/ratelimit.go
pkg/apis/policyattachment/v1alpha2/healthcheck.go
pkg/apis/policyattachment/v1alpha2/retry.go

fix: nullable fields of CRD

---

pkg/gateway/processor/v2/utils.go
tests/e2e/e2e_statefulsets_test.go

fixed isolation policy with fgw.
Done
| …

fixed isolation policy with fgw.

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go

refactor: cleanup unused values

---

pkg/gateway/fgw/config.go

feat: GEP-1731 HTTPRoute Retry support

---

pkg/connector/ktog/gateway.go

fix connector source check.
Done
| Upgrade …

fix connector source check.

---

cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
pkg/apis/connector/v1alpha1/consul.go
pkg/apis/connector/v1alpha1/eureka.go
pkg/apis/connector/v1alpha1/nacos.go
pkg/apis/connector/v1alpha1/zz_generated.deepcopy.go
pkg/connector/cli/config.go
pkg/connector/controller.go
pkg/connector/ctok/syncer.go
pkg/sidecar/providers/pipy/repo/util.go

add fixed service port option.
Done
| …

add fixed service port option.

---

pkg/catalog/catalog.go
pkg/catalog/isolation.go
pkg/catalog/mock_catalog_generated.go
pkg/catalog/types.go
pkg/gateway/processor/v2/config.go
pkg/gateway/processor/v2/utils.go
pkg/messaging/broker.go
pkg/repo/client.go
pkg/repo/types.go
pkg/sidecar/providers/pipy/proxy.go
pkg/sidecar/providers/pipy/repo/codebase/modules/inbound-http-routing.js
pkg/sidecar/providers/pipy/repo/codebase/modules/outbound-http-routing.js
pkg/sidecar/providers/pipy/repo/jobs.go

fix issues(isolation policy, pjs and stale files).

---

pkg/gateway/processor/v2/config.go
pkg/repo/client.go
pkg/repo/types.go

fix: delete stale files from gateway codebase

---

pkg/controllers/gateway/v1/gateway_controller.go
pkg/repo/client.go

feature: delete codebase when gateway is deleted

---

pkg/gateway/fgw/config.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/tlsroute.go
pkg/gateway/processor/v2/udproute.go
pkg/gateway/processor/v2/utils.go

fix: output weight field of 0-weight backend

---

pkg/gateway/processor/v2/backends.go
pkg/k8s/client.go
pkg/smi/client.go

fixed traffic split for connector.
Done
| …

fixed traffic split for connector.

---

go.mod
go.sum
pkg/controllers/gateway/v1/gateway_controller.go
pkg/controllers/gateway/v1/types.go
pkg/controllers/gateway/v1beta1/referencegrant_controller.go
pkg/gateway/fgw/config.go
pkg/gateway/processor/v2/backend_tls_policy.go
pkg/gateway/processor/v2/gateway.go
pkg/gateway/processor/v2/generator.go
pkg/gateway/processor/v2/types.go
pkg/gateway/status/gw/gateway.go
pkg/gateway/status/routes/processor.go
pkg/gateway/status/routes/types.go
pkg/gateway/types/types.go
pkg/gateway/utils/certificates.go
pkg/gateway/utils/gateway.go
pkg/gateway/utils/referencegrants.go
tests/e2e/e2e_gatewayapi_test.go

feat: [GEP-3155] Complete Backend mutual TLS Configuration

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

[backport] build(deps): bump pipy to 1.5.2 (#399)

---

pkg/constants/constants.go
pkg/controllers/gateway/v1/grpcroute_controller.go
pkg/controllers/gateway/v1/httproute_controller.go
pkg/controllers/gateway/v1alpha2/tcproute_controller.go
pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
pkg/controllers/gateway/v1alpha2/udproute_controller.go
pkg/gateway/fgw/config.go
pkg/gateway/processor/v2/backends.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/tlsroute.go
pkg/gateway/processor/v2/types.go
pkg/gateway/processor/v2/udproute.go
pkg/gateway/status/routes/backendlb.go
pkg/gateway/status/routes/backendtls.go
pkg/gateway/status/routes/grpcroute.go
pkg/gateway/status/routes/healthcheck.go
pkg/gateway/status/routes/httproute.go
pkg/gateway/status/routes/processor.go
pkg/gateway/status/routes/retry.go
pkg/gateway/status/routes/tcproute.go
pkg/gateway/status/routes/udproute.go
pkg/gateway/utils/backends.go

feat: backend protocol selection

---

pkg/gateway/processor/v2/backends.go
pkg/gateway/processor/v2/tlsroute.go
pkg/gateway/processor/v2/utils.go

feat: transform appProtocol to FGW format when generating configuration

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy to 1.5.3

---

cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_gatewayconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_machineconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
pkg/apis/connector/v1alpha1/consul.go
pkg/apis/connector/v1alpha1/eureka.go
pkg/apis/connector/v1alpha1/gateway.go
pkg/apis/connector/v1alpha1/machine.go
pkg/apis/connector/v1alpha1/nacos.go
pkg/apis/connector/v1alpha1/types.go
pkg/apis/connector/v1alpha1/zz_generated.deepcopy.go
pkg/connector/ctok/syncer.go
pkg/connector/ktog/gateway.go
pkg/controllers/connector/v1alpha1/types.go

1. add service target port merge.
2. fix connector source check.
3. add imagePullSecrets for connector.
Done
| …

fix issues.

---

charts/connector/README.md
charts/connector/templates/_helpers.tpl
charts/connector/templates/deployment.yaml
charts/connector/values.schema.json
charts/connector/values.yaml

remove init container from connector deployment.
Done
| Tests …

remove init container from connector deployment.

---

charts/connector/README.md
charts/connector/templates/_helpers.tpl
charts/connector/templates/deployment.yaml
charts/connector/values.schema.json
charts/connector/values.yaml

[cherry-pick] remove init container from connector deployment. (#415)

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/gateway/processor/v2/backends.go
pkg/gateway/processor/v2/config.go
pkg/gateway/processor/v2/generator.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/types.go
pkg/gateway/processor/v2/udproute.go

feat: conditionally drop route rule if no available backends

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
codegen/gen-crd-client.sh
pkg/apis/config/v1alpha3/mesh_config.go
pkg/gateway/processor/v2/backends.go
pkg/gateway/processor/v2/config.go
pkg/gateway/processor/v2/generator.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/types.go
pkg/gateway/processor/v2/udproute.go

…kends (#419)
fix: merge issue
fix: codegen
| Tests                      | [ ] …

[cherry-pick] feat: conditionally drop route rule if no available backends

---

Makefile

ci(deps): bump trivy from 0.23.0 to 0.57.0

---

Makefile

* ci(deps): bump trivy from 0.23.0 to 0.57.0
* ci(deps): trivy db repository
* ci(deps): trivy cmd
* ci(deps): trivy cmd
* ci(deps): trivy cmd
--------- …

[backport] ci(deps): bump trivy from 0.23.0 to 0.57.0 (#422)

---

pkg/gateway/processor/v2/generator.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/types.go
pkg/gateway/processor/v2/udproute.go

fix: copy HTTPRouteFilters

---

pkg/gateway/processor/v2/generator.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/types.go
pkg/gateway/processor/v2/udproute.go

* fix: copy HTTPRouteFilters
* refactor: housekeeping
---------
| Tests …

[cherry-pick] fix: copy HTTPRouteFilters (#426)

---

pkg/controllers/gateway/v1/grpcroute_controller.go
pkg/controllers/gateway/v1/httproute_controller.go
pkg/controllers/gateway/v1alpha2/tcproute_controller.go
pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
pkg/controllers/gateway/v1alpha2/udproute_controller.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/health_check_policy.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/tlsroute.go
pkg/gateway/processor/v2/udproute.go
pkg/gateway/status/policies/policy.go
pkg/gateway/status/routes/backendlb.go
pkg/gateway/status/routes/backendtls.go
pkg/gateway/status/routes/healthcheck.go
pkg/gateway/status/routes/processor.go
pkg/gateway/status/routes/route.go
pkg/gateway/status/types.go
pkg/gateway/utils/gateway.go

refactor: simplify methods

---

charts/gateway/README.md
charts/gateway/templates/daemonset.yaml
charts/gateway/values.yaml
pkg/controllers/gateway/v1/gateway_controller.go
pkg/helm/types.go

feat: support deploy Gateway as DaemonSet

---

pkg/controllers/gateway/v1/gateway_controller.go

fix: merge values when gateway parameters is empty

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.3 to 1.5.4

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.4 to 1.5.5

---

.github/workflows/main.yml

ci: free space before running test cases

---

.github/workflows/main.yml

* ci: free space before running test cases
* ci: free space before running test cases
--------- …

[backport] ci: free space before running test cases (#441)

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml
Makefile

ci: switch to goreleaser for publishing release

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml
Makefile

* ci: switch to goreleaser for publishing release
* fix: release notes
* fix: generate-cli-chart
* fix: goreleaser config
* feat: add debug
* refactor: add debug message
* feat: use goreleaser name template func
* fix: a typo
* feat: use goreleaser name template func
* feat: add zip archives
* fix: config
---------
| Install …

[cherry-pick] ci: switch to goreleaser for publishing release (#445)

---

.github/workflows/release.yml
.goreleaser.yaml

feat: generate and publish a homebrew-tap recipe for fsm cli

---

.goreleaser.yaml

fix: go build ldflags

---

.github/workflows/release.yml
.goreleaser.yaml

…m cli (#448)
* feat: generate and publish a homebrew-tap recipe for fsm cli
* fix: brew ids
* fix: publishing brew tap
---------
| Security …

[cherry-pick] feat: generate and publish a homebrew-tap recipe for fsm cli

---

dockerfiles/Dockerfile.fsm-bootstrap
dockerfiles/Dockerfile.fsm-connector
dockerfiles/Dockerfile.fsm-controller
dockerfiles/Dockerfile.fsm-crds
dockerfiles/Dockerfile.fsm-curl
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-healthcheck
dockerfiles/Dockerfile.fsm-ingress
dockerfiles/Dockerfile.fsm-injector
dockerfiles/Dockerfile.fsm-preinstall
dockerfiles/Dockerfile.fsm-sidecar-init
dockerfiles/Dockerfile.fsm-xnetmgmt
dockerfiles/Dockerfile.pipy-debian
dockerfiles/Dockerfile.pipy-nonroot

fix: BUILDPLATFORM of final image

---

pkg/gateway/utils/endpointslices.go

feat: gateway backends support IPv6 addresses

---

pkg/controllers/flb/utils.go

[cherry-pick] fix: support IPv6 external address

---

.github/workflows/build-pipy-nonroot.yml
.github/workflows/release.yml

…1 to 5.6.1 (#456)
Bumps [crazy-max/ghaction-docker-meta](https://github.com/crazy-max/ghaction-docker-meta) from 5.5.1 to 5.6.1.
- [Release notes](https://github.com/crazy-max/ghaction-docker-meta/releases)
- [Commits](https://github.com/crazy-max/ghaction-docker-meta/compare/v5.5.1...v5.6.1)
---
updated-dependencies:
- dependency-name: crazy-max/ghaction-docker-meta dependency-type: direct:production update-type: version-update:semver-minor ...
| Demo                       | [ ] …

[backport] build(deps): Bump crazy-max/ghaction-docker-meta from 5.5.1 to 5.6.1.

---

pkg/gateway/utils/endpointslices.go

[backport] feat: gateway backends support IPv6 addresses (#454)

---

.goreleaser.yaml

feat: skip upload brew formula if no PAT

---

.goreleaser.yaml

* feat: skip upload brew formula if no PAT
* feat: skip upload brew formula if no PAT
--------- …

[cherry-pick] feat: skip upload brew formula if no PAT (#464)

---

cmd/fsm-controller/fsm-controller.go
pkg/dns/handler.go
pkg/dns/resolver.go
pkg/dns/server.go
pkg/k8s/client.go
pkg/k8s/mock_controller_generated.go
pkg/k8s/types.go
pkg/sidecar/providers/pipy/driver/pipy_container.go
pkg/sidecar/providers/pipy/repo/jobs.go

[cherry-pick] fix local dns proxy. (#467)

---

pkg/constants/constants.go
pkg/gateway/processor/v2/utils.go
pkg/gateway/status/routes/grpcroute.go
pkg/gateway/status/routes/httproute.go
pkg/gateway/status/routes/methods.go
pkg/gateway/status/routes/tcproute.go
pkg/gateway/status/routes/types.go
pkg/gateway/status/routes/udproute.go
pkg/gateway/status/routes/utils.go

feat: support new app protocols

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-check.yml

ci: add pr-title-checker action

---

.github/workflows/dco.yml

ci: add dco action

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-check.yml

* ci: add pr-title-checker action
* feat: Add comment to fix PR title
---------
fix: pr-title-checker permission
fix: pr-title-checker permission
| …

[backport] ci: add pr-title-checker action (#472)

---

.github/workflows/dco.yml

ci: add dco action
ci: add dco action
| …

ci: add dco action (#475)[backport] 

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-check.yml

ci: adjust the regex of validating PR title

---

.github/workflows/dco.yml

ci: exclude github bot email from DCO check

---

.github/workflows/build-pipy-nonroot.yml
.github/workflows/release.yml

….10.0 (#483)
* ci: exclude github bot email (#484)
* build(deps): Bump docker/build-push-action from 6.9.0 to 6.10.0
Bumps [docker/build-push-action](https://github.com/docker/build-push-action) from 6.9.0 to 6.10.0.
- [Release notes](https://github.com/docker/build-push-action/releases)
- [Commits](https://github.com/docker/build-push-action/compare/v6.9.0...v6.10.0)
---
updated-dependencies:
- dependency-name: docker/build-push-action dependency-type: direct:production update-type: version-update:semver-minor ...
---------
| Certificate Management …

[BACKPORT] build(deps): Bump docker/build-push-action from 6.9.0 to 6.10.0

---

pkg/dns/handler.go
pkg/dns/resolver.go
pkg/dns/server.go
pkg/sidecar/v1/providers/pipy/driver/pipy_container.go

[CHERRY-PICK] fix: local dns proxy. (#487)

---

.github/pr-title-checker-config.json
.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

ci: automatically cherry-pick/backport PR

---

.github/pr-title-checker-config.json
.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

[backport] ci: automatically cherry-pick/backport PR (#489)

---

.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

[backport] fix: labels pattern of cherry-pick & backport workflow (#490)

---

.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

feat: add names for workflow

---

.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

Backport #493 to `release/v1.4`.

[backport] feat: add names for workflow

---

.github/workflows/build-pipy-images.yml

ci: rename workflow of building pipy euler and nonroot images

---

.github/workflows/pr-title-check.yml

Backport #496 to `release/v1.4`.

[backport] ci: set continue-on-error to false in pr-title-checker action

---

.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

ci: trigger cherry-pick/backport by labels on PR

---

.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

Backport #499 to `release/v1.4`.

[backport] ci: trigger cherry-pick/backport by labels on PR

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.5 to 1.5.7

---

.github/dependabot.yml

ci: enhance the dependabot configuration

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/constants/constants.go
pkg/injector/webhook.go
pkg/k8s/client.go
pkg/k8s/client_test.go
pkg/manager/listeners/client.go
pkg/messaging/broker.go
pkg/messaging/types.go
pkg/models/types.go
pkg/sidecar/v1/providers/pipy/driver/pipy_container.go
pkg/sidecar/v1/providers/pipy/driver/sidecar.go
pkg/sidecar/v1/providers/pipy/proxy.go
pkg/sidecar/v1/providers/pipy/proxy_test.go
pkg/sidecar/v1/providers/pipy/registry/announcement_handlers_test.go
pkg/sidecar/v1/providers/pipy/registry/registry.go
pkg/sidecar/v1/providers/pipy/registry/services.go
pkg/sidecar/v1/providers/pipy/repo/broadcast.go
pkg/sidecar/v1/providers/pipy/repo/inform.go
pkg/sidecar/v1/providers/pipy/repo/jobs.go
pkg/sidecar/v1/providers/pipy/repo/policy.go

add HoldApplicationUntilProxyStarts and GracefulExitUntilDownstreamEnds features. 
Done …

feat: add HoldApplicationUntilProxyStarts and GracefulExitUntilDownstreamEnds features. 

---

.github/workflows/build-pipy-nonroot.yml
.github/workflows/release.yml

[backport] build(deps): Bump docker/setup-buildx-action from 3.7.1 to 3.8.0 (#518)

---

.github/dependabot.yml

[backport] ci: fix syntax error in dependabot.yml (#520)

---

.github/dependabot.yml

ci: add dependency update PR to milestone v1.5.0

---

.github/dependabot.yml

ci: set open-pull-requests-limit of version updates to 10

---

.github/dependabot.yml

ci: set the frequency of version updates to daily

---

.github/dependabot.yml

ci: set time and timezone for running dependabot

---

.github/dependabot.yml

ci: groups gorm dependencies together

---

go.mod

refactor: re-organize go dependencies in go.mod

---

pkg/connector/provider/nacos.go

one nacos connection registers a unique service instance.
| Tests …

[cherry-pick] fix: one nacos connection registers a unique service instance. (#570)

---

go.mod
go.sum

build(deps): bump github.com/cilium/ebpf from v0.16.0 to v0.17.1

---

pkg/gateway/repo/broadcast.go

refactor: adjust the sliding timer of Gateway

---

pkg/injector/init_container.go
pkg/injector/iptables.go
pkg/injector/iptables_test.go
scripts/vm/README.md
scripts/vm/run-sidecar.sh

fix run-sidecar.sh for vm.
Done
| Upgrade …

fix: run-sidecar.sh for vm.

---

pkg/injector/init_container.go
pkg/injector/iptables.go
pkg/injector/iptables_test.go
scripts/vm/README.md
scripts/vm/run-sidecar.sh

* fix: run-sidecar.sh for vm.
* fix: run-sidecar.sh for vm.
* fix: run-sidecar.sh for vm.
* fix: run-sidecar.sh for vm.
---------
| Security …

[cherry-pick] fix: run-sidecar.sh for vm. (#577)

---

pkg/connector/cli/client.go
pkg/connector/controller.go
pkg/connector/ctok/source.go
pkg/connector/ctok/syncer.go
pkg/connector/discovery.go
pkg/connector/ktoc/source.go
pkg/connector/ktoc/syncer.go
pkg/connector/metadata.go
pkg/connector/provider/consul.go
pkg/connector/provider/eureka.go
pkg/connector/provider/machine.go
pkg/connector/provider/nacos.go
pkg/connector/provider/zookeeper.go
pkg/connector/types.go
pkg/sidecar/v1/providers/pipy/registry/services.go
pkg/zookeeper/discovery/dubbo/adaptor.go
pkg/zookeeper/discovery/dubbo/instance.go
pkg/zookeeper/discovery/dubbo/mapfield.go

refactor connector to support generics protocols.
Done
| Tests …

refactor: connector to support generics protocols.

---

pkg/connector/provider/consul.go

fix sync consul health check service
Done …

fix: sync consul health check service

---

CODEOWNERS

[backport] docs: Update CODEOWNERS

---

.mergify.yml

ci: template of backport PR title

---

.mergify.yml

[backport] ci: template of backport PR title (#596)

---

.github/slash-commands-config.yml
.github/workflows/slash-commands.yml

ci: slash commands workflow

---

.github/workflows/slash-commands.yml

ci: restrict only admin user can run slash commands workflow

---

.mergify.yml

ci(Mergify): copy PRs those merged into main to release/v1.5

---

pkg/k8s/client.go
pkg/sidecar/v1/providers/pipy/repo/util.go

fix via gateway for vm
Done
| Upgrade …

fix: via gateway for vm

---

go.mod
go.sum

…to v27.5.0+incompatible
| Upgrade …

build(deps): bump github.com/docker/docker from v27.2.1+incompatible to v27.5.0+incompatible

---

scripts/get-k3d-logs.sh
tests/framework/common.go

test: grab logs of k3d cluster

---

README.md

skip ci
| Upgrade                    | [ ] …

docs: add more approaches of getting FSM CLI

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.8 to 1.5.9

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.8 to 1.5.9(release/v1.4)

---

pkg/messaging/broker.go
pkg/sidecar/v1/providers/pipy/driver/pipy_container.go

1. fix nil pointer.
2. fix lifecycle scripts.
Done
| Tests …

fix: nil pointer and lifecycle scripts.

---

go.mod
go.sum

build(deps): bump sigs.k8s.io/controller-runtime from 0.19.4 to 0.19.5

---

pkg/xnetwork/xnet/maps/acl.go

fix acl sys assignment.
Done
| Upgrade …

fix: acl sys assignment.

---

docs/tests/gateway-api/README.md

docs: add testcase for resolving DNS

---

dockerfiles/Dockerfile.fsm-bootstrap
dockerfiles/Dockerfile.fsm-connector
dockerfiles/Dockerfile.fsm-controller
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-injector
dockerfiles/Dockerfile.fsm-preinstall
dockerfiles/Dockerfile.fsm-xnetmgmt
pkg/sidecar/v2/broadcast.go
pkg/sidecar/v2/dns.go
pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/job.go
pkg/xnetwork/xnet/maps/cfg.go
pkg/xnetwork/xnet/maps/nat.go
pkg/xnetwork/xnet/maps/types.go
pkg/xnetwork/xnet/util/ip.go

xnet supports ipv6 traffic interception.
Done
| Tests                      | [ …

feat: xnet supports ipv6 traffic interception.

---

pkg/gateway/processor/v2/gateway.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/utils.go

fix(v1.4): generate consistent unique key for filters

---

pkg/gateway/processor/v2/gateway.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/tcproute.go
pkg/gateway/processor/v2/udproute.go
pkg/gateway/processor/v2/utils.go

fix: generate consistent unique key for filters

---

pkg/gateway/processor/v2/config.go
pkg/gateway/processor/v2/gateway.go
pkg/gateway/processor/v2/grpcroute.go
pkg/gateway/processor/v2/httproute.go
pkg/gateway/processor/v2/processor.go
pkg/gateway/processor/v2/utils.go
pkg/ingress/providers/pipy/cache/cache.go
pkg/manager/repo/repo.go
pkg/manager/utils/util.go
pkg/repo/client.go

feat(v1.4): incremental update gateway codebase

---

dockerfiles/Dockerfile.fsm-xnetmgmt

fix: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
fix: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
| …

fix: qemu: uncaught target signal 11 (Segmentation fault) - core dumped

---

dockerfiles/Dockerfile.fsm-bootstrap
dockerfiles/Dockerfile.fsm-connector
dockerfiles/Dockerfile.fsm-controller
dockerfiles/Dockerfile.fsm-crds
dockerfiles/Dockerfile.fsm-curl
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-healthcheck
dockerfiles/Dockerfile.fsm-ingress
dockerfiles/Dockerfile.fsm-injector
dockerfiles/Dockerfile.fsm-preinstall
dockerfiles/Dockerfile.fsm-sidecar-init
dockerfiles/Dockerfile.fsm-xnetmgmt
dockerfiles/Dockerfile.pipy-debian
dockerfiles/Dockerfile.pipy-nonroot

build(deps): bump external Dockerfile frontend to latest 1.x

---

.goreleaser.yaml

ci: fix deprecated goreleaser config properties

---

.github/workflows/release.yml

ci: dispatch fsm-release event to flomesh-io/xnet

---

.github/workflows/release.yml

ci: fix PAT for repository dispatch event

---

charts/gateway/templates/daemonset.yaml
pkg/connector/ctok/source.go
pkg/connector/ctok/syncer.go
pkg/connector/discovery.go
pkg/connector/ktoc/source.go
pkg/connector/metadata.go
pkg/connector/provider/zookeeper.go
pkg/k8s/client.go
pkg/zookeeper/discovery/k8s/adaptor.go
pkg/zookeeper/discovery/k8s/instance.go
pkg/zookeeper/discovery/k8s/mapfield.go

Support registration and discovery of http services based on zookeeper.
Done
| …

feat: support registration and discovery of http services based on zookeeper

---

cmd/fsm-controller/fsm-controller.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/controllers/gateway/v1/gateway_methods.go
pkg/helm/helm.go

fix: Gateway Parameter Priority and Updating

---

charts/connector/README.md
charts/connector/templates/_helpers.tpl
charts/connector/templates/deployment.yaml
charts/connector/values.schema.json
charts/connector/values.yaml
cmd/fsm-controller/fsm-controller.go
pkg/context/types.go
pkg/controllers/connector/v1alpha1/types.go

fix fsmConnector service account name render.
Done
| Tests …

fix: fsmConnector service account name render.

---

pkg/utils/env.go
tests/framework/common.go
tests/framework/types.go

test: write k3d node logs to stdout if needed

---

.github/workflows/release-image.yml
.github/workflows/release.yml

fix: release workflow

---

pkg/connector/cli/sync.go

fix cluster ip selector for k8s 1.19
Done …

fix: cluster ip selector for k8s 1.19

---

.mergify.yml

fix: mergify config of auto merging

---

pkg/gateway/processor/v2/backends.go

fix cross cluster endpoints for k8s 1.19
Done
| Tests                      | [ …

fix: cross cluster endpoints for k8s 1.19

---

Dockerfile
Makefile
go.mod
pkg/certificate/providers/config_test.go
pkg/health/health.go
pkg/mcs/remote/types.go
scripts/test-w-coverage.sh
tests/framework/common.go

build(deps): bump golang version from 1.23 to 1.24

---

charts/gateway/templates/daemonset.yaml
charts/gateway/templates/deployment.yaml
cmd/fsm-gateway/fsm-gateway.go
pkg/constants/constants.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/gateway/processor/triggers/gateway/gateways_trigger.go
pkg/gateway/processor/v2/config.go
pkg/gateway/utils/gateway.go

feat: gateway readiness probe

---

charts/gateway/templates/deployment.yaml
cmd/fsm-gateway/fsm-gateway.go
pkg/constants/constants.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/gateway/processor/triggers/gateway/gateways_trigger.go
pkg/gateway/processor/v2/config.go
pkg/gateway/utils/gateway.go

[backport] feat: gateway readiness probe

---

.github/workflows/e2e.yml
.github/workflows/ghcr.yml
.github/workflows/main.yml
scripts/k3d-with-registry.sh
tests/framework/k3d-cluster.yaml

fix: replace hardcoded repository owner with context value

---

charts/gateway/templates/daemonset.yaml
charts/gateway/templates/deployment.yaml

feat: increase failureThreshold of gateway startup probe

---

pkg/gateway/processor/v2/filters.go

feat: handle empty filter config

---

.github/workflows/e2e.yml

ci: exclude fsm-demo-*.tar from loading into docker for e2e test

---

.github/workflows/e2e.yml
.github/workflows/main.yml
.github/workflows/release-image.yml

ci: free disk space controlled by action variables

---

.github/workflows/build-pipy-images.yml

ci: use github hosted arm64 runner

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.9 to 1.5.10

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.9 to 1.5.10(release-v1.4)

---

.github/workflows/e2e.yml
.github/workflows/main.yml

ci: improve the performance by only download required images at each job

---

.github/workflows/main.yml
Makefile

ci: simplify trivy scan images workflow

---

cmd/fsm-controller/fsm-controller.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/helm/helm.go

[backport]fix: Gateway Parameter Priority and Updating

---

pkg/k8s/client.go
pkg/k8s/mock_controller_generated.go
pkg/k8s/types.go
pkg/sidecar/v2/dns.go
pkg/sidecar/v2/server.go

fix monitor for dns proxy upstreams.
Done …

fix: monitor for dns proxy upstreams.

---

go.mod
pkg/connector/ctok/source.go
pkg/connector/ktoc/syncer.go

fix connector retries.
Done
| Upgrade …

fix: connector retries(release-v1.4).

---

pkg/sidecar/v2/dns.go

fix dns proxy upstream selection.
Done
| …

fix: dns proxy upstream selection.

---

pkg/sidecar/v2/acl.go
pkg/sidecar/v2/dns.go
pkg/sidecar/v2/server.go

support ipv6 dns traffic interception.
Done
| Tests                      | [ ] …

feat: support ipv6 dns traffic interception.

---

pkg/connector/provider/nacos.go
pkg/sidecar/v2/acl.go
pkg/sidecar/v2/dns.go
pkg/sidecar/v2/server.go

compatible with nacos server config
Done
| …

fix: compatible with nacos server config

---

charts/fsm/README.md
charts/fsm/values.yaml
go.mod
go.sum
pkg/sidecar/v2/dns.go
pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/probe.go

fix nat endpoints probe and k3s cni bin.
Done
| Tests                      | [ …

fix: nat endpoints probe and k3s cni bin.

---

pkg/sidecar/v2/dns.go
pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/xnat.go
pkg/xnetwork/xnet/arp/announce.go

support pods on eip announce nodes to route traffic through elastic ips.
Done
| …

feat: pods on eip announce nodes to route traffic through elastic ips.

---

charts/fsm/templates/fsm-xnetwork.yaml
pkg/sidecar/v2/dns.go
pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/server.go
pkg/xnetwork/xnet/volume/types.go

fix xnat cache key
Done
| Upgrade …

fix: xnat cache key

---

pkg/gateway/processor/v2/backends.go

fix: only list EndpointSlice in the namespace of the service

---

pkg/gateway/fgw/config.go

fix: default time unit in config should be seconds

---

pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/e4lbtopo.go

optimize eip layout algorithm.
Done
| …

fix: eip layout algorithm.

---

pkg/controllers/connector/v1alpha1/consul_controller.go
pkg/controllers/connector/v1alpha1/eureka_controller.go
pkg/controllers/connector/v1alpha1/gateway_controller.go
pkg/controllers/connector/v1alpha1/machine_controller.go
pkg/controllers/connector/v1alpha1/nacos_controller.go
pkg/controllers/connector/v1alpha1/types.go
pkg/controllers/connector/v1alpha1/zookeeper_controller.go
pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/e4lbtopo.go

Optimize Elastic IP-based traffic routing implementations on EIP-bound announcement nodes.
Done …

fix: optimize Elastic IP-based traffic routing implementations on EIP-bound announcement nodes.

---

.github/dependabot.yml

ci: dependabot default assign created PR to milestone v1.6.0

---

.github/workflows/main.yml

…tions-deps group (#841)
build(deps): Bump golangci/golangci-lint-action
Bumps the actions-deps group with 1 update: [golangci/golangci-lint-action](https://github.com/golangci/golangci-lint-action).
Updates `golangci/golangci-lint-action` from 7 to 8
- [Release notes](https://github.com/golangci/golangci-lint-action/releases)
- [Commits](https://github.com/golangci/golangci-lint-action/compare/v7...v8)
---
updated-dependencies:
- dependency-name: golangci/golangci-lint-action dependency-version: '8' dependency-type: direct:production update-type: version-update:semver-major dependency-group: actions-deps ...
| CI System …

[backport] build(deps): Bump golangci/golangci-lint-action from 7 to 8 

---

pkg/k8s/client.go
pkg/k8s/client_test.go
pkg/providers/kube/client.go
pkg/providers/kube/client_test.go
pkg/sidecar/v1/providers/pipy/driver/sidecar.go
pkg/sidecar/v1/providers/pipy/registry/services.go

fix: ha issues.

---

pkg/k8s/client.go
pkg/k8s/client_test.go
pkg/providers/kube/client.go
pkg/providers/kube/client_test.go
pkg/sidecar/providers/pipy/driver/sidecar.go
pkg/sidecar/providers/pipy/registry/services.go

fix: ha issues.(release/v1.4)

---

pkg/sidecar/v2/nodes.go

fix node network unavailable check.
Done
| …

fix: node network unavailable check.

---

pkg/sidecar/v2/nodes.go

[cherry-pick] fix: node network unavailable check. (#856)

---

pkg/k8s/client.go
pkg/k8s/client_test.go
pkg/providers/kube/client.go
pkg/providers/kube/client_test.go
pkg/sidecar/v1/providers/pipy/driver/sidecar.go
pkg/sidecar/v1/providers/pipy/registry/services.go

* fix ha issues.
* fix ha issues.
---------
| Tests                      | [ ] …

[cherry-pick] fix: ha issues. (#848)

---

pkg/connector/ktoc/source.go

fix choose ports.
Done
| Upgrade …

fix: choose ports(release/v1.5).

---

go.mod
go.sum

…o 2.3.0 (#873)
build(deps): Bump github.com/nacos-group/nacos-sdk-go/v2
Bumps [github.com/nacos-group/nacos-sdk-go/v2](https://github.com/nacos-group/nacos-sdk-go) from 2.2.9 to 2.3.0.
- [Release notes](https://github.com/nacos-group/nacos-sdk-go/releases)
- [Commits](https://github.com/nacos-group/nacos-sdk-go/compare/v2.2.9...v2.3.0)
---
updated-dependencies:
- dependency-name: github.com/nacos-group/nacos-sdk-go/v2 dependency-version: 2.3.0 dependency-type: direct:production update-type: version-update:semver-minor ...
| Certificate Management     | …

[backport] build(deps): Bump github.com/nacos-group/nacos-sdk-go/v2 from 2.2.9 to 2.3.0

---

cmd/fsm-bootstrap/crds/gatewayclasses.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/gateways.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/grpcroutes.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/httproutes.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/referencegrants.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/tcproutes.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/tlsroutes.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/udproutes.gateway.networking.k8s.io.yaml
cmd/fsm-bootstrap/crds/xbackendtrafficpolicies.gateway.networking.x-k8s.io.yaml
cmd/fsm-bootstrap/crds/xlistenersets.gateway.networking.x-k8s.io.yaml
cmd/fsm-bootstrap/raw/gateway-api.yaml
cmd/fsm-bootstrap/raw/kustomization.yaml

build(deps): bump GatewayAPI crds from v1.2.1 to v1.3.0

---

.github/workflows/main.yml
.mergify.yml
tests/e2e/e2e_retry_policy_test.go
tests/framework/common_traffic.go

test: fix retry e2e test frequently failed issue

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods_test.go
scripts/k3d-multicluster-deploy-apps.sh
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy from 1.5.10 to 1.5.12

---

pkg/controllers/gateway/v1/gateway_controller.go

fix: correct condition check for Gateway DaemonSet scheduling

---

pkg/dns/handler.go

fix: dns proxy.

---

pkg/dns/handler.go

fix: dns proxy.(release/v1.5)

---

.github/workflows/release.yml

fix: update release permissions to allow write access for contents

---

pkg/gateway/processor/mock_processor_generated.go
pkg/gateway/processor/triggers/gateway/gateways_trigger.go
pkg/gateway/processor/types.go
pkg/gateway/processor/v2/processor.go

fix: cleanup files hash when gateway is deleted

---

cmd/fsm-bootstrap/crds/connector.flomesh.io_consulconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_eurekaconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_nacosconnectors.yaml
cmd/fsm-bootstrap/crds/connector.flomesh.io_zookeeperconnectors.yaml
pkg/apis/connector/v1alpha1/consul.go
pkg/apis/connector/v1alpha1/eureka.go
pkg/apis/connector/v1alpha1/nacos.go
pkg/apis/connector/v1alpha1/zookeeper.go
pkg/apis/connector/v1alpha1/zz_generated.deepcopy.go
pkg/connector/cli/config.go
pkg/connector/controller.go
pkg/connector/ktoc/source.go

support filterLabels and filterAnnotations for KtoCSource.
Done
| Tests …

feat: filterLabels and filterAnnotations for KtoCSource.

---

pkg/connector/provider/eureka.go

fix eureka register cache.
Done
| Upgrade …

fix: eureka register cache(release/1.5).

---

cmd/fsm-gateway/fsm-gateway.go

fix: improve PIPY process management and logging in fsm-gateway

---

pkg/connector/ktoc/source.go
pkg/connector/provider/eureka.go
pkg/sidecar/v2/broadcast.go
pkg/sidecar/v2/e4lb.go
pkg/sidecar/v2/probe.go
pkg/xnetwork/xnet/route/arping_linux.go

fix: issues

---

pkg/connector/provider/nacos.go

fix the connection to nacos is not properly closed.
Done
| Tests …

fix: the connection to nacos is not properly closed.

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods_test.go
scripts/k3d-multicluster-deploy-apps.sh
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

build(deps): bump pipy to 1.5.14

---

.mergify.yml

feat: Add backport action for release/v1.6 branch

---

README.md

docs: Add FSM version and supported GatewayAPI version mapping

---

demo/deploy-kafka.sh
demo/deploy-zookeeper.sh
tests/e2e/e2e_statefulsets_test.go

…ilegacy
| Upgrade                    | [ …

fix: update Helm chart repositories for Kafka and Zookeeper to bitnamilegacy
