flomesh-io/fsm

.github/workflows/codeql-analysis.yml
.github/workflows/main.yml

ci: watch branch release/v* to trigger GitHub actions

---

.github/workflows/main.yml
Makefile
charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha1/mesh_config.go
pkg/apis/config/v1alpha2/mesh_config.go
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/manager/listeners/client.go
pkg/messaging/broker.go
pkg/sidecar/providers/pipy/repo/codebase/connect-tcp.js
pkg/sidecar/providers/pipy/repo/codebase/main.js
pkg/sidecar/providers/pipy/repo/jobs.go
pkg/sidecar/providers/pipy/repo/policy.go
pkg/sidecar/providers/pipy/repo/types.go

Add SidecarTimeout to MeshConfig.
Done
| …

Add SidecarTimeout to MeshConfig.

---

cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml

fix: regenerate CRD manifests

---

pkg/manager/utils/tls.go

fix: invalid default TLS cert for ingress

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
go.mod
go.sum
pkg/apis/config/v1alpha3/mesh_config.go
pkg/gateway/cache/config.go
pkg/gateway/cache/types.go
pkg/gateway/cache/utils.go
pkg/messaging/broker.go

feat: add feature flag to enable/disable Gateway agent service

---

charts/fsm/README.md
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/gateway/cache/config.go
pkg/gateway/routecfg/types.go
pkg/manager/listeners/client.go
pkg/messaging/broker.go

feat: add more options to configure FGW

---

charts/gateway/templates/deployment.yaml
charts/namespaced-ingress/templates/deployment.yaml
pkg/configurator/methods.go
pkg/configurator/mock_client_generated.go
pkg/configurator/types.go
pkg/manager/listeners/client.go

fix: overwrite curl image value in gateway and namespaced-ingress charts

---

pkg/controllers/flb/service_controller.go

fix: only filter endpoints by protocol of service port

---

pkg/controllers/gateway/v1beta1/gateway_controller.go
pkg/controllers/policyattachment/v1alpha1/accesscontrolpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/circuitbreakingpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/faultinjectionpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/gatewaytlspolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/healthcheckpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/loadbalancerpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/ratelimitpolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/retrypolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/sessionstickypolicy_controller.go
pkg/controllers/policyattachment/v1alpha1/upstreamtlspolicy_controller.go
pkg/gateway/cache/config.go
pkg/gateway/cache/grpcroute.go
pkg/gateway/cache/httproute.go
pkg/gateway/cache/methods.go
pkg/gateway/cache/policies.go
pkg/gateway/cache/utils.go
pkg/gateway/routecfg/types.go

Across all rules specified on applicable Routes, precedence must be given to the match having:
“Exact” path match.
“Prefix” path match with largest number of characters.
Method match.
Largest number of header matches.
Largest number of query param matches.
Note: The precedence of RegularExpression path matches are implementation-specific.
If ties still exist across multiple Routes, matching precedence MUST be determined in order of the following criteria, continuing on ties:
The oldest Route based on creation timestamp.
The Route appearing first in alphabetical order by “{namespace}/{name}”.

feat: sort traffic match conditions of route

---

charts/fsm/templates/fsm-rbac.yaml
cmd/cli/uninstall_mesh.go

fix: clean up all FSM CRDs upon uninstallation

---

docs/api_reference/config.json

update api reference doc generation config

---

charts/fsm/README.md
charts/fsm/values.yaml

Explain `defaultAlgo` option about FLB.
| Documentation              | [ X] |
| …

[chore] Update FLB docs for defaultAlgo.

---

pkg/controllers/flb/service_controller.go

fix: incorrect update annotation of FLB svc

---

cmd/fsm-ingress/fsm-ingress.go

fix: minimum k8s for fsm-ingress

---

pkg/controllers/flb/event_handlers.go

fix: don't delete svc from cache if failed to delete svc from FLB

---

pkg/controllers/flb/event_handlers.go
pkg/controllers/flb/service_controller.go

fix: remove service hash annotation if it's not a FLB svc anymore

---

pkg/controllers/flb/event_handlers.go

fix: clean up LoadBalancer address if it's not FLB svc anymore

---

.github/workflows/main.yml
charts/fsm/README.md
charts/fsm/templates/fsm-rbac.yaml
charts/fsm/templates/preset-mesh-config.yaml
charts/fsm/values.schema.json
charts/fsm/values.yaml
charts/gateway/templates/deployment.yaml
charts/gateway/templates/pod-disruption-budget.yaml
charts/gateway/templates/role.yaml
charts/gateway/templates/rolebinding.yaml
charts/gateway/templates/route.yaml
charts/gateway/templates/service-tcp.yaml
charts/gateway/templates/service-udp.yaml
charts/gateway/templates/serviceaccount.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/connector/ctok/endpoint.go
pkg/controllers/gateway/v1/gateway_controller.go
pkg/controllers/servicelb/service_controller.go
pkg/gateway/cache/cache.go
pkg/gateway/cache/endpoints_trigger.go
pkg/gateway/cache/endpointslices_trigger.go
pkg/gateway/cache/methods.go
pkg/gateway/cache/processor.go
pkg/gateway/cache/types.go
pkg/gateway/cache/utils.go
pkg/utils/ip.go
pkg/version/utils.go
tests/e2e/e2e_gatewayapi_test.go

…under 1.21
| Upgrade                    | …

feat: use Endpoints to calculate backend addresses if k8s version is under 1.21

---

cmd/fsm-connector/fsm-connector.go
pkg/connector/ctok/endpoint.go
pkg/connector/ctok/syncer.go
pkg/messaging/broker.go

remove useless k8s informer
Done
| Upgrade …

remove useless k8s informer

---

charts/fsm/grafana/pipy/dashboards/fsm-control-plane.json
charts/fsm/grafana/pipy/dashboards/fsm-data-plane-performance.json
charts/fsm/grafana/pipy/dashboards/fsm-mesh-sidecar-details.json
charts/fsm/templates/fsm-deployment.yaml
charts/fsm/templates/grafana-configmap.yaml
charts/fsm/templates/prometheus-configmap.yaml

Since FSM does not support`fsm.sidecarClass` no longer, the legacy configuration results Grafana Dashboard lost.
There are also changes for dashboard metrics which result panel rendering issue.
| Observability              | [x] |
| Performance                | [ …

fix: Grafana dashboard issue due to legacy sidecarClass configuration

---

pkg/gateway/processor/v2/backend_lb_policy.go
pkg/gateway/processor/v2/backend_tls_policy.go
pkg/gateway/processor/v2/health_check_policy.go
pkg/gateway/processor/v2/retry_policy.go
pkg/gateway/utils/policies.go

fix: check policy status when generating config

---

pkg/constants/constants.go
pkg/sidecar/providers/pipy/driver/pipy_container.go

…tation for pod and namespace.
Support specifying sidecar's image by "flomesh.io/sidecar-image" annotation for pod and namespace.
| Security …

Support specifying sidecar's image for pod and namespace.

---

cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

fix(deps): bump pipy of all images to 1.5.0

---

cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
pkg/apis/config/v1alpha3/mesh_config.go
pkg/catalog/inbound_traffic_policies_test.go
pkg/catalog/outbound_traffic_policies_test.go
pkg/k8s/util.go
pkg/k8s/util_test.go

add mustWithNamespace option into meshconfig.
Done
| Tests …

add mustWithNamespace option into meshconfig.

---

pkg/controllers/gateway/v1/grpcroute_controller.go
pkg/controllers/gateway/v1/httproute_controller.go
pkg/controllers/gateway/v1alpha2/tcproute_controller.go
pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
pkg/controllers/gateway/v1alpha2/udproute_controller.go

fix: trigger xRoutes to reconcile when gateway/backend status changed

---

pkg/controllers/gateway/v1/grpcroute_controller.go
pkg/controllers/gateway/v1/httproute_controller.go
pkg/controllers/gateway/v1alpha2/tcproute_controller.go
pkg/controllers/gateway/v1alpha2/tlsroute_controller.go
pkg/controllers/gateway/v1alpha2/udproute_controller.go

…tus changed (#435)
* fix: trigger xRoutes to reconcile when gateway status changed
* fix: trigger xRoutes to reconcile when backend status changed
---------
| SMI Policy                 | [ …

[backport] fix: trigger xRoutes to reconcile when gateway/backend status changed

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

[backport] build(deps): bump pipy from 1.5.3 to 1.5.4 (#437)

---

cmd/fsm-controller/fsm-controller.go
pkg/dns/handler.go
pkg/dns/resolver.go
pkg/dns/server.go
pkg/k8s/client.go
pkg/k8s/mock_controller_generated.go
pkg/k8s/types.go
pkg/sidecar/providers/pipy/driver/pipy_container.go
pkg/sidecar/providers/pipy/repo/jobs.go

fix local dns proxy.
Done
| Upgrade …

fix local dns proxy.

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-check.yml

* ci: adjust the regex of validating PR title
* docs: update comment of invalid PR title
---------
| Sidecar …

[BACKPORT] ci: adjust the regex of validating PR title (#479)

---

pkg/dns/handler.go
pkg/dns/resolver.go
pkg/dns/server.go
pkg/sidecar/providers/pipy/driver/pipy_container.go

fix local dns proxy.
Done
| Upgrade …

fix: local dns proxy.

---

.github/workflows/backport.yml
.github/workflows/cherry-pick.yml

fix: labels pattern of cherry-pick & backport workflow

---

pkg/controllers/gateway/v1/gateway_controller.go
pkg/gateway/processor/v2/config.go
pkg/gateway/processor/v2/triggers.go
pkg/manager/repo/repo.go
pkg/repo/client.go

fix: commit after deriving codebase and updating configs

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

Backport #503 to `release/v1.4`.

[backport] build(deps): bump pipy from 1.5.5 to 1.5.7

---

charts/fsm/README.md
charts/fsm/values.yaml
cmd/fsm-bootstrap/crds/config.flomesh.io_meshconfigs.yaml
dockerfiles/Dockerfile.fsm-gateway
dockerfiles/Dockerfile.fsm-ingress
docs/tests/gateway-api/README.md
pkg/apis/config/v1alpha3/mesh_config.go
tests/e2e/e2e_fsm_ingress_test.go
tests/e2e/e2e_gatewayapi_test.go

[backport] build(deps): bump pipy from 1.5.7 to 1.5.8 (#508)

---

.github/dependabot.yml

ci: fix syntax error in dependabot.yml

---

.github/dependabot.yml

ci: groups and ignores dependencies updates

---

pkg/connector/discovery.go
pkg/connector/provider/nacos.go

fix: one nacos connection registers a unique service instance.
Done
| Tests …

fix: one nacos connection registers a unique service instance.

---

pkg/messaging/broker.go
pkg/messaging/types.go

fix HoldApplicationUntilProxyStarts feature.
Done
| Tests …

fix: HoldApplicationUntilProxyStarts feature.

---

.mergify.yml

* ci(Mergify): configuration update
* Update .mergify.yml
* Update .mergify.yml
--------- …

[backport] ci(Mergify): configuration update (#588)

---

.mergify.yml

ci(Mergify): enforce linear history

---

.github/slash-commands-config.yml
.github/workflows/slash-commands.yml

[backport] ci: slash commands workflow (#599)

---

pkg/k8s/client.go
pkg/k8s/types.go

fix virtual machine monitor.
Done
| …

fix: virtual machine monitor.

---

pkg/k8s/client.go
pkg/sidecar/providers/pipy/repo/util.go

fix via gateway for vm
Done
| Upgrade …

fix: via gateway for vm

---

.github/workflows/main.yml
.mergify.yml
tests/framework/common.go

ci: optimize e2e test workflow

---

pkg/catalog/outbound_traffic_policies.go

ignore mesh services without ready endpoints.
Done
| Tests …

refactor: ignore mesh services without ready endpoints.

---

charts/connector/templates/_helpers.tpl
charts/connector/values.schema.json
charts/fsm/templates/_helpers.tpl
charts/fsm/values.schema.json
charts/gateway/templates/_helpers.tpl
charts/namespaced-ingress/templates/_helpers.tpl

In some scenario, the image would retag to number only format. Current helm chart does not support it.

feat: support Int type image tag

---

go.mod
pkg/connector/ctok/source.go
pkg/connector/ktoc/syncer.go

fix connector retries.
Done
| Upgrade …

fix: connector retries.

---

.github/workflows/e2e.yml
.github/workflows/main.yml
go.mod
pkg/utils/image.go
scripts/k3d-with-registry.sh
tests/framework/common.go
tests/framework/k3d-cluster.yaml
tests/framework/types.go

fix: increase k3d cluster CIDR range from /24 to /16

---

pkg/gateway/fgw/config.go

[backport] fix: default time unit in config should be seconds(release/v1.4)

---

.github/workflows/e2e.yml
tests/e2e/e2e_retry_policy_test.go

…havior
| Upgrade                    | [ ] …

ci: add LOAD_IMAGES_INTO_CLUSTER variable to control image loading behavior

---

pkg/connector/ktoc/source.go
pkg/connector/provider/nacos.go

Potential fix for [https://github.com/flomesh-io/fsm/security/code-scanning/82](https://github.com/flomesh-io/fsm/security/code-scanning/82)
To fix the issue, we need to ensure that the value of `port` is within the valid range for `connector.MicroServicePort` before performing the conversion. This can be achieved by:
1. Using `strconv.ParseInt` with a specified bit size (e.g., 32 bits) to parse the string representation of `ins.Port`.
2. Adding bounds checks to ensure the parsed value is within the valid range for `connector.MicroServicePort` (e.g., `math.MinInt32` to `math.MaxInt32` for a 32-bit integer).
3. Returning an error or a default value if the bounds check fails.
The changes will be applied to the `Deregister` and `Register` methods where the `port` variable is used.
--- …

fix: Incorrect conversion between integer types

---

pkg/connector/ktoc/source.go
pkg/controllers/connector/v1alpha1/consul_controller.go
pkg/controllers/connector/v1alpha1/eureka_controller.go
pkg/controllers/connector/v1alpha1/gateway_controller.go
pkg/controllers/connector/v1alpha1/machine_controller.go
pkg/controllers/connector/v1alpha1/nacos_controller.go
pkg/controllers/connector/v1alpha1/types.go
pkg/controllers/connector/v1alpha1/zookeeper_controller.go

fix repeated deploy connectors after controller restarts.
Done
| Tests …

fix: repeated deploy connectors after controller restarts.

---

tests/e2e/e2e_statefulsets_test.go

fix: add image tag of zk for statefulset in e2e tests
